name: Deploy Bootstrap page to GitHub Pages.
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Generate test coverage xml report
        run: dotnet test --collect:"XPlat Code Coverage"