name: Generate test coverage xml report.
on: [push]
jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Generate test coverage xml report
        run: 
          dotnet test --collect:"XPlat Code Coverage"

      - name: Archive production artifacts
        uses: codecov/codecov-action@v1
        with:
          files: /home/runner/work/console-calculator/console-calculator/**/TestResults/**/coverage.cobertura.xml
          flags: unittests # optional
          fail_ci_if_error: true
          verbose: true
        # uses: actions/upload-artifact@v2
        # with:
        #   name: code-coverage-report
        #   path: /home/runner/work/console-calculator/console-calculator/**/TestResults/**/coverage.cobertura.xml
